elements = [    
    {'name': "Hydrogen", 'symbol': "H", 'number': 1, 'weight': 1.008, 'group': 1, 'period': 1, 'type': 'reactive-non-metal', 'fact': "Hydrogen is the most abundant element in the universe."},
    {'name': "Helium", 'symbol': "He", 'number': 2, 'weight': 4.0026, 'group': 18, 'period': 1, 'type': 'noble-gas', 'fact': "Helium is the second lightest and second most abundant element in the observable universe."},
    {'name': "Lithium", 'symbol': "Li", 'number': 3, 'weight': 6.94, 'group': 1, 'period': 2, 'type': 'alkali', 'fact': "Lithium is used in rechargeable batteries for mobile phones and electric vehicles."},
    {'name': "Beryllium", 'symbol': "Be", 'number': 4, 'weight': 9.0122, 'group': 2, 'period': 2, 'type': 'alkaline-earth', 'fact': "Beryllium is used in aerospace components due to its light weight and stiffness."},
    {'name': "Boron", 'symbol': "B", 'number': 5, 'weight': 10.81, 'group': 13, 'period': 2, 'type': 'metalloid', 'fact': "Boron is essential for plant growth and is used in fertilizers."},
    {'name': "Carbon", 'symbol': "C", 'number': 6, 'weight': 12.011, 'group': 14, 'period': 2, 'type': 'reactive-non-metal', 'fact': "Carbon is the basis of all known life on Earth."},
    {'name': "Nitrogen", 'symbol': "N", 'number': 7, 'weight': 14.007, 'group': 15, 'period': 2, 'type': 'reactive-non-metal', 'fact': "Nitrogen makes up about 78% of the Earth's atmosphere."},
    {'name': "Oxygen", 'symbol': "O", 'number': 8, 'weight': 15.999, 'group': 16, 'period': 2, 'type': 'reactive-non-metal', 'fact': "'Oxygen' comes from the Greek word 'oxus' meaning 'acid-forming'."},
    {'name': "Fluorine", 'symbol': "F", 'number': 9, 'weight': 18.998, 'group': 17, 'period': 2, 'type': 'reactive-non-metal', 'fact': 'Fluorine is the most electronegative element.'},
    {'name': "Neon", 'symbol': "Ne", 'number': 10, 'weight': 20.180, 'group': 18, 'period': 2, 'type': 'noble-gas', 'fact': "Neon is used in neon signs and high-voltage indicators."},
    {'name': "Sodium", 'symbol': "Na", 'number': 11, 'weight': 22.990, 'group': 1, 'period': 3, 'type': 'alkali', 'fact': "Sodium is essential for life and is found in table salt."},
    {'name': "Magnesium", 'symbol': "Mg", 'number': 12, 'weight': 24.305, 'group': 2, 'period': 3, 'type': 'alkaline-earth', 'fact': "Magnesium is used in fireworks to produce a bright white light."},
    {'name': "Aluminum", 'symbol': "Al", 'number': 13, 'weight': 26.982, 'group': 13, 'period': 3, 'type': 'post-transition-metal', 'fact': "Aluminum is the most abundant metal in the Earth's crust."},
    {'name': "Silicon", 'symbol': "Si", 'number': 14, 'weight': 28.085, 'group': 14, 'period': 3, 'type': 'metalloid', 'fact': "Silicon is a key component of computer chips."},
    {'name': "Phosphorus", 'symbol': "P", 'number': 15, 'weight': 30.974, 'group': 15, 'period': 3, 'type': 'reactive-non-metal', 'fact': "'Phosphorus' comes from the Greek word meaning 'light bearer'."},
    {'name': "Sulfur", 'symbol': "S", 'number': 16, 'weight': 32.06, 'group': 16, 'period': 3, 'type': 'reactive-non-metal', 'fact': "'Sulfur' has been known since ancient times and was called 'brimstone'."},
    {'name': "Chlorine", 'symbol': "Cl", 'number': 17, 'weight': 35.45, 'group': 17, 'period': 3, 'type': 'reactive-non-metal', 'fact': "'Chlorine' was first discovered in the late 18th century by Carl Wilhelm Scheele."},
    {'name': "Argon", 'symbol': "Ar", 'number': 18, 'weight': 39.948, 'group': 18, 'period': 3, 'type': 'noble-gas', 'fact': "Argon makes up about 0.93% of the Earth's atmosphere."},
    {'name': "Potassium", 'symbol': "K", 'number': 19, 'weight': 39.098, 'group': 1, 'period': 4, 'type': 'alkali', 'fact': "Potassium is essential for plant growth and health."},
    {'name': "Calcium", 'symbol': "Ca", 'number': 20, 'weight': 40.078, 'group': 2, 'period': 4, 'type': 'alkaline-earth', 'fact': "Calcium is vital for bone health and muscle function."},
    {'name': "Scandium", 'symbol': "Sc", 'number': 21, 'weight': 44.956, 'group': 3, 'period': 4, 'type': 'transition-metal', 'fact': "Scandium is used in aerospace components due to its strength-to-weight ratio."},
    {'name': "Titanium", 'symbol': "Ti", 'number': 22, 'weight': 47.867, 'group': 4, 'period': 4, 'type': 'transition-metal', 'fact': "Titanium is known for its high strength-to-weight ratio and corrosion resistance."},
    {'name': "Vanadium", 'symbol': "V", 'number': 23, 'weight': 50.942, 'group': 5, 'period': 4, 'type': 'transition-metal', 'fact': "Vanadium is used to produce strong steel alloys."},
    {'name': "Chromium", 'symbol': "Cr", 'number': 24, 'weight': 52, 'group': 6, 'period': 4, 'type': 'transition-metal', 'fact': "Chromium gives stainless steel its shiny appearance and corrosion resistance."},
    {'name': "Manganese", 'symbol': "Mn", 'number': 25, 'weight': 54.938, 'group': 7, 'period': 4, 'type': 'transition-metal', 'fact': "Manganese is essential for bone formation and metabolism."},
    {'name': "Iron", 'symbol': "Fe", 'number': 26, 'weight': 55.845, 'group': 8, 'period': 4, 'type': 'transition-metal', 'fact': "Iron is crucial for blood production in humans."},
    {'name': "Cobalt", 'symbol': "Co", 'number': 27, 'weight': 58.933, 'group': 9, 'period': 4, 'type': 'transition-metal', 'fact': "Cobalt gives blue color to glass and ceramics."},
    {'name': "Nickel", 'symbol': "Ni", 'number': 28, 'weight': 58.693, 'group': 10, 'period': 4, 'type': 'transition-metal', 'fact': "Nickel is used to make stainless steel and coins."},
    {'name': "Copper", 'symbol': "Cu", 'number': 29, 'weight': 63.546, 'group': 11, 'period': 4, 'type': 'transition-metal', 'fact': "Copper has excellent electrical conductivity."},
    {'name': "Zinc", 'symbol': "Zn", 'number': 30, 'weight': 65.38, 'group': 12, 'period': 4, 'type': 'transition-metal', 'fact': "Zinc is important for immune function."},
    {'name': 'Gallium', 'symbol': 'Ga', 'number': 31, 'weight': 69.723, 'group': 13, 'period': 4, 'type': 'post-transition-metal', 'fact': 'Gallium melts just above room temperature.'},
    {'name': 'Germanium', 'symbol': 'Ge', 'number': 32, 'weight': 72.63, 'group': 14, 'period': 4, 'type': 'metalloid', 'fact': 'Germanium is used in fiber optics.'},
    {'name': 'Arsenic', 'symbol': 'As', 'number': 33, 'weight': 74.922, 'group': 15, 'period': 4, 'type': 'metalloid', 'fact': 'Arsenic has been used as a poison throughout history.'},
    {'name': 'Selenium', 'symbol': 'Se', 'number': 34, 'weight': 78.971, 'group': 16, 'period': 4, 'type': 'reactive-non-metal', 'fact': 'Selenium is important for antioxidant enzymes.'},
    {'name': 'Bromine', 'symbol': 'Br', 'number': 35, 'weight': 79.904, 'group': 17, 'period': 4, 'type': 'reactive-non-metal', 'fact': 'Bromine is the only liquid nonmetal at room temperature.'},
    {'name': 'Krypton', 'symbol': 'Kr', 'number': 36, 'weight': 83.798, 'group': 18, 'period': 4, 'type': 'noble-gas', 'fact': 'Krypton can be used in high-performance flashlights.'},
    {'name': 'Rubidium', 'symbol': 'Rb', 'number': 37, 'weight': 85.468, 'group': 1, 'period': 5, 'type': 'alkali', 'fact': 'Rubidium reacts explosively with water.'},
    {'name': 'Strontium', 'symbol': 'Sr', 'number': 38, 'weight': 87.62, 'group': 2, 'period': 5, 'type': 'alkaline-earth', 'fact': 'Strontium compounds produce bright red flames.'},
    {'name': 'Yttrium', 'symbol': 'Y', 'number': 39, 'weight': 88.906, 'group': 3, 'period': 5, 'type': 'transition-metal', 'fact': 'Yttrium is used in LEDs and phosphors.'},
    {'name': 'Zirconium', 'symbol': 'Zr', 'number': 40, 'weight': 91.224, 'group': 4, 'period': 5, 'type': 'transition-metal', 'fact': 'Zirconium is highly resistant to corrosion and is used in nuclear reactors.'},
    {'name': 'Niobium', 'symbol': 'Nb', 'number': 41, 'weight': 92.906, 'group': 5, 'period': 5, 'type': 'transition-metal', 'fact': 'Niobium is used in superconducting materials.'},
    {'name': 'Molybdenum', 'symbol': 'Mo', 'number': 42, 'weight': 95.95, 'group': 6, 'period': 5, 'type': 'transition-metal', 'fact': 'Molybdenum has the highest melting point of all pure elements.'},
    {'name': 'Technetium', 'symbol': 'Tc', 'number': 43, 'weight': 98.0, 'group': 7, 'period': 5, 'type': 'transition-metal', 'fact': 'Technetium was the first artificially produced element.'},
    {'name': 'Ruthenium', 'symbol': 'Ru', 'number': 44, 'weight': 101.07, 'group': 8, 'period': 5, 'type': 'transition-metal', 'fact': 'Ruthenium is used in electronics and as a catalyst.'},
    {'name': 'Rhodium', 'symbol': 'Rh', 'number': 45, 'weight': 102.91, 'group': 9, 'period': 5, 'type': 'transition-metal', 'fact': 'Rhodium is one of the rarest metals and is highly reflective.'},
    {'name': 'Palladium', 'symbol': 'Pd', 'number': 46, 'weight': 106.42, 'group': 10, 'period': 5, 'type': 'transition-metal', 'fact': 'Palladium is used in catalytic converters in cars.'},
    {'name': 'Silver', 'symbol': 'Ag', 'number': 47, 'weight': 107.87, 'group': 11, 'period': 5, 'type': 'transition-metal', 'fact': 'Silver has the highest electrical conductivity of any metal.'},
    {'name': 'Cadmium', 'symbol': 'Cd', 'number': 48, 'weight': 112.41, 'group': 12, 'period': 5, 'type': 'transition-metal', 'fact': 'Cadmium is used in rechargeable nickel-cadmium batteries.'},
    {'name': 'Indium', 'symbol': 'In', 'number': 49, 'weight': 114.82, 'group': 13, 'period': 5, 'type': 'post-transition-metal', 'fact': 'Indium is used in LCD screens and solders.'},
    {'name': 'Tin', 'symbol': 'Sn', 'number': 50, 'weight': 118.71, 'group': 14, 'period': 5, 'type': 'post-transition-metal', 'fact': 'Tin is used to coat other metals to prevent corrosion.'},
    {'name': 'Antimony', 'symbol': 'Sb', 'number': 51, 'weight': 121.76, 'group': 15, 'period': 5, 'type': 'metalloid', 'fact': 'Antimony is used in flame retardants.'},
    {'name': 'Tellurium', 'symbol': 'Te', 'number': 52, 'weight': 127.60, 'group': 16, 'period': 5, 'type': 'metalloid', 'fact': 'Tellurium is used in metal alloys and as a semiconductor.'},
    {'name': 'Iodine', 'symbol': 'I', 'number': 53, 'weight': 126.90, 'group': 17, 'period': 5, 'type': 'reactive-non-metal', 'fact': 'Iodine is essential for thyroid hormone production.'},
    {'name': 'Xenon', 'symbol': 'Xe', 'number': 54, 'weight': 131.29, 'group': 18, 'period': 5, 'type': 'noble-gas', 'fact': 'Xenon is used in high-intensity discharge lamps.'},
    {'name': 'Cesium', 'symbol': 'Cs', 'number': 55, 'weight': 132.91, 'group': 1, 'period': 6, 'type': 'alkali', 'fact': 'Cesium has the lowest ionization energy of all elements.'},
    {'name': 'Barium', 'symbol': 'Ba', 'number': 56, 'weight': 137.33, 'group': 2, 'period': 6, 'type': 'alkaline-earth', 'fact': 'Barium compounds are used in medical imaging.'},
    {'name': 'Lanthanum', 'symbol': 'La', 'number': 57, 'weight': 138.91, 'group': 3, 'period': 6, 'type': 'lanthanide', 'fact': 'Lanthanum is used in camera lenses and catalysts.'},
    {'name': 'Cerium', 'symbol': 'Ce', 'number': 58, 'weight': 140.12, 'group': 4, 'period': 8, 'type': 'lanthanide', 'fact': 'Cerium is used in polishing powders and catalysts.'},
    {'name': 'Praseodymium', 'symbol': 'Pr', 'number': 59, 'weight': 140.91, 'group': 5, 'period': 8, 'type': 'lanthanide', 'fact': 'Praseodymium is used to create strong magnets.'},
    {'name': 'Neodymium', 'symbol': 'Nd', 'number': 60, 'weight': 144.24, 'group': 6, 'period': 8, 'type': 'lanthanide', 'fact': 'Neodymium is known for its powerful permanent magnets.'},
    {'name': 'Promethium', 'symbol': 'Pm', 'number': 61, 'weight': 145.0, 'group': 7, 'period': 8, 'type': 'lanthanide', 'fact': 'Promethium is the only lanthanide that is radioactive and does not have stable isotopes.'},
    {'name': 'Samarium', 'symbol': 'Sm', 'number': 62, 'weight': 150.36, 'group': 8, 'period': 8, 'type': 'lanthanide', 'fact': 'Samarium is used in magnets and as a neutron absorber in nuclear reactors.'},
    {'name': 'Europium', 'symbol': 'Eu', 'number': 63, 'weight': 151.98, 'group': 9, 'period': 8, 'type': 'lanthanide', 'fact': 'Europium is used in phosphorescent materials and is responsible for the red color in television screens.'},
    {'name': 'Gadolinium', 'symbol': 'Gd', 'number': 64, 'weight': 157.25, 'group': 10, 'period': 8, 'type': 'lanthanide', 'fact': 'Gadolinium is used as a contrast agent in MRI scans.'},
    {'name': 'Terbium', 'symbol': 'Tb', 'number': 65, 'weight': 158.93, 'group': 11, 'period': 8, 'type': 'lanthanide', 'fact': 'Terbium is used in solid-state devices and green phosphors.'},
    {'name': 'Dysprosium', 'symbol': 'Dy', 'number': 66, 'weight': 162.50, 'group': 12, 'period': 8, 'type': 'lanthanide', 'fact': 'Dysprosium is used in high-performance magnets.'},
    {'name': 'Holmium', 'symbol': 'Ho', 'number': 67, 'weight': 164.93, 'group': 13, 'period': 8, 'type': 'lanthanide', 'fact': 'Holmium has the highest magnetic susceptibility of any element.'},
    {'name': 'Erbium', 'symbol': 'Er', 'number': 68, 'weight': 167.26, 'group': 14, 'period': 8, 'type': 'lanthanide', 'fact': 'Erbium is used in fiber optic technology and as a laser source.'},
    {'name': 'Thulium', 'symbol': 'Tm', 'number': 69, 'weight': 168.93, 'group': 15, 'period': 8, 'type': 'lanthanide', 'fact': 'Thulium is the least abundant lanthanide and is used in medical imaging.'},
    {'name': 'Ytterbium', 'symbol': 'Yb', 'number': 70, 'weight': 173.04, 'group': 16, 'period': 8, 'type': 'lanthanide', 'fact': 'Ytterbium is used in certain types of lasers.'},
    {'name': 'Lutetium', 'symbol': 'Lu', 'number': 71, 'weight': 175.0, 'group': 17, 'period': 8, 'type': 'lanthanide', 'fact': 'Lutetium is used in cancer treatment and as a catalyst.'},
    {'name': 'Hafnium', 'symbol': 'Hf', 'number': 72, 'weight': 178.49, 'group': 4, 'period': 6, 'type': 'transition-metal', 'fact': 'Hafnium is used in nuclear reactors for its neutron-absorbing properties.'},
    {'name': 'Tantalum', 'symbol': 'Ta', 'number': 73, 'weight': 180.95, 'group': 5, 'period': 6, 'type': 'transition-metal', 'fact': 'Tantalum is highly corrosion-resistant and is used in electronics.'},
    {'name': 'Tungsten', 'symbol': 'W', 'number': 74, 'weight': 183.84, 'group': 6, 'period': 6, 'type': 'transition-metal', 'fact': 'Tungsten has the highest melting point of all metals.'},
    {'name': 'Rhenium', 'symbol': 'Re', 'number': 75, 'weight': 186.21, 'group': 7, 'period': 6, 'type': 'transition-metal', 'fact': 'Rhenium is used in high-temperature superalloys.'},
    {'name': 'Osmium', 'symbol': 'Os', 'number': 76, 'weight': 190.23, 'group': 8, 'period': 6, 'type': 'transition-metal', 'fact': 'Osmium is the densest naturally occurring element.'},
    {'name': 'Iridium', 'symbol': 'Ir', 'number': 77, 'weight': 192.22, 'group': 9, 'period': 6, 'type': 'transition-metal', 'fact': 'Iridium is highly resistant to corrosion and oxidation.'},
    {'name': 'Platinum', 'symbol': 'Pt', 'number': 78, 'weight': 195.08, 'group': 10, 'period': 6, 'type': 'transition-metal', 'fact': 'Platinum is widely used in catalytic converters.'},
    {'name': 'Gold', 'symbol': 'Au', 'number': 79, 'weight': 196.97, 'group': 11, 'period': 6, 'type': 'transition-metal', 'fact': 'Gold has been valued for its rarity and beauty for thousands of years.'},
    {'name': 'Mercury', 'symbol': 'Hg', 'number': 80, 'weight': 200.59, 'group': 12, 'period': 6, 'type': 'transition-metal', 'fact': 'Mercury is the only metal that is liquid at room temperature.'},
    {'name': 'Thallium', 'symbol': 'Tl', 'number': 81, 'weight': 204.38, 'group': 13, 'period': 6, 'type': 'post-transition-metal', 'fact': 'Thallium was once used in rat poisons.'},
    {'name': 'Lead', 'symbol': 'Pb', 'number': 82, 'weight': 207.2, 'group': 14, 'period': 6, 'type': 'post-transition-metal', 'fact': 'Lead was widely used in paints and pipes before its toxicity was known.'},
    {'name': 'Bismuth', 'symbol': 'Bi', 'number': 83, 'weight': 208.98, 'group': 15, 'period': 6, 'type': 'post-transition-metal', 'fact': 'Bismuth has low toxicity compared to other heavy metals.'},
    {'name': 'Polonium', 'symbol': 'Po', 'number': 84, 'weight': 209.98, 'group': 16, 'period': 6, 'type': 'post-transition-metal', 'fact': 'Polonium is highly radioactive and was discovered by Marie Curie.'},
    {'name': 'Astatine', 'symbol': 'At', 'number': 85, 'weight': 210.0, 'group': 17, 'period': 6, 'type': 'post-transition-metal', 'fact': 'Astatine is one of the rarest naturally occurring elements on Earth.'},
    {'name': 'Radon', 'symbol': 'Rn', 'number': 86, 'weight': 222.0, 'group': 18, 'period': 6, 'type': 'noble-gas', 'fact': 'Radon is a radioactive gas that can accumulate in homes.'},
    {'name': 'Francium', 'symbol': 'Fr', 'number': 87, 'weight': 223.0, 'group': 1, 'period': 7, 'type': 'alkali', 'fact': 'Francium is extremely rare and highly radioactive.'},
    {'name': 'Radium', 'symbol': 'Ra', 'number': 88, 'weight': 226.0, 'group': 2, 'period': 7, 'type': 'alkaline-earth', 'fact': 'Radium was once used in luminous paints.'},
    {'name': 'Actinium', 'symbol': 'Ac', 'number': 89, 'weight': 227.0, 'group': 3, 'period': 7, 'type': 'actinide', 'fact': 'Actinium glows faintly due to its radioactivity.'},
    {'name': 'Thorium', 'symbol': 'Th', 'number': 90, 'weight': 232.04, 'group': 4, 'period': 9, 'type': 'actinide', 'fact': 'Thorium can be used as a nuclear fuel source.'},
    {'name': 'Protactinium', 'symbol': 'Pa', 'number': 91, 'weight': 231.04, 'group': 5, 'period': 9, 'type': 'actinide', 'fact': 'Protactinium is used in nuclear reactors and has a very long half-life.'},
    {'name': 'Uranium', 'symbol': 'U', 'number': 92, 'weight': 238.03, 'group': 6, 'period': 9, 'type': 'actinide', 'fact': 'Uranium is the primary fuel for nuclear power plants.'},
    {'name': 'Neptunium', 'symbol': 'Np', 'number': 93, 'weight': 237.0, 'group': 7, 'period': 9, 'type': 'actinide', 'fact': 'Neptunium is used in some types of nuclear reactors and as a neutron source.'},
    {'name': 'Plutonium', 'symbol': 'Pu', 'number': 94, 'weight': 244.0, 'group': 8, 'period': 9, 'type': 'actinide', 'fact': 'Plutonium is used in nuclear weapons and as a fuel in some nuclear reactors.'},
    {'name': 'Americium', 'symbol': 'Am', 'number': 95, 'weight': 243.0, 'group': 9, 'period': 9, 'type': 'actinide', 'fact': 'Americium is used in smoke detectors and as a neutron source.'},
    {'name': 'Curium', 'symbol': 'Cm', 'number': 96, 'weight': 247.0, 'group': 10, 'period': 9, 'type': 'actinide', 'fact': 'Curium was named after Marie and Pierre Curie for their contributions to radioactivity.'},
    {'name': 'Berkelium', 'symbol': 'Bk', 'number': 97, 'weight': 247.0, 'group': 11, 'period': 9, 'type': 'actinide', 'fact': 'Berkelium is used in research and has no significant commercial applications.'},
    {'name': 'Californium', 'symbol': 'Cf', 'number': 98, 'weight': 251.0, 'group': 12, 'period': 9, 'type': 'actinide', 'fact': 'Californium is used in neutron moisture gauges and as a neutron source.'},
    {'name': 'Einsteinium', 'symbol': 'Es', 'number': 99, 'weight': 252.0, 'group': 13, 'period': 9, 'type': 'actinide', 'fact': 'Einsteinium was discovered in the debris of the first hydrogen bomb explosion.'},
    {'name': 'Fermium', 'symbol': 'Fm', 'number': 100, 'weight': 257.0, 'group': 14, 'period': 9, 'type': 'actinide', 'fact': 'Fermium was named after physicist Enrico Fermi.'},
    {'name': 'Mendelevium', 'symbol': 'Md', 'number': 101, 'weight': 258.0, 'group': 15, 'period': 9, 'type': 'actinide', 'fact': 'Mendelevium was the first element to be made by bombarding einsteinium with alpha particles.'},
    {'name': 'Nobelium', 'symbol': 'No', 'number': 102, 'weight': 259.0, 'group': 16, 'period': 9, 'type': 'actinide', 'fact': 'Nobelium was named after Alfred Nobel, the inventor of dynamite.'},
    {'name': 'Lawrencium', 'symbol': 'Lr', 'number': 103, 'weight': 262.0, 'group': 17, 'period': 9, 'type': 'actinide', 'fact': 'Lawrencium was named after Ernest O. Lawrence, who invented the cyclotron.'},
    {'name': 'Rutherfordium', 'symbol': 'Rf', 'number': 104, 'weight': 267.0, 'group': 4, 'period': 7, 'type': 'transition-metal', 'fact': 'Rutherfordium was named after physicist Ernest Rutherford.'},
    {'name': 'Dubnium', 'symbol': 'Db', 'number': 105, 'weight': 270.0, 'group': 5, 'period': 7, 'type': 'transition-metal', 'fact': 'Dubnium was named after the town of Dubna in Russia.'},
    {'name': 'Seaborgium', 'symbol': 'Sg', 'number': 106, 'weight': 271.0, 'group': 6, 'period': 7, 'type': 'transition-metal', 'fact': 'Seaborgium was named after Glenn T. Seaborg, who contributed to the discovery of several actinides.'},
    {'name': 'Bohrium', 'symbol': 'Bh', 'number': 107, 'weight': 270.0, 'group': 7, 'period': 7, 'type': 'transition-metal', 'fact': 'Bohrium was named in honor of Niels Bohr for his contributions to atomic structure.'},
    {'name': 'Hassium', 'symbol': 'Hs', 'number': 108, 'weight': 277.0, 'group': 8, 'period': 7, 'type': 'transition-metal', 'fact': 'Hassium is highly radioactive and has no significant commercial applications.'},
    {'name': 'Meitnerium', 'symbol': 'Mt', 'number': 109, 'weight': 278.0, 'group': 9, 'period': 7, 'type': 'unknown', 'fact': 'Meitnerium was named after physicist Lise Meitner.'},
    {'name': 'Darmstadtium', 'symbol': 'Ds', 'number': 110, 'weight': 281.0, 'group': 10, 'period': 7, 'type': 'unknown', 'fact': 'Darmstadtium was named after the city of Darmstadt in Germany.'},
    {'name': 'Roentgenium', 'symbol': 'Rg', 'number': 111, 'weight': 280.0, 'group': 11, 'period': 7, 'type': 'unknown', 'fact': 'Roentgenium was named after Wilhelm Röntgen, discoverer of X-rays.'},
    {'name': 'Copernicium', 'symbol': 'Cn', 'number': 112, 'weight': 285.0, 'group': 12, 'period': 7, 'type': 'unknown', 'fact': 'Copernicium was named after astronomer Nicolaus Copernicus.'},
    {'name': 'Nihonium', 'symbol': 'Nh', 'number': 113, 'weight': 284.0, 'group': 13, 'period': 7, 'type': 'unknown', 'fact': 'Nihonium was named after Japan (Nihon) where it was discovered.'},
    {'name': 'Flerovium', 'symbol': 'Fl', 'number': 114, 'weight': 289.0, 'group': 14, 'period': 7, 'type': 'unknown', 'fact': 'Flerovium is named after the Flerov Laboratory of Nuclear Reactions in Russia.'},
    {'name': 'Moscovium', 'symbol': 'Mc', 'number': 115, 'weight': 288.0, 'group': 15, 'period': 7, 'type': 'unknown', 'fact': 'Moscovium was named after Moscow and is part of the group of superheavy elements.'},
    {'name': 'Livermorium', 'symbol': 'Lv', 'number': 116, 'weight': 293.0, 'group': 16, 'period': 7, 'type': 'unknown', 'fact': 'Livermorium was named after Lawrence Livermore National Laboratory and is highly radioactive.'},
    {'name': 'Tennessine', 'symbol': 'Ts', 'number': 117, 'weight': 294.0, 'group': 17, 'period': 7, 'type': 'unknown', 'fact': 'Tennessine was named after the state of Tennessee and is one of the heaviest known elements.'},
    {'name': 'Oganesson', 'symbol': 'Og', 'number': 118, 'weight': 294.0, 'group': 18, 'period': 7, 'type': 'unknown', 'fact': 'Oganesson is a synthetic element and is extremely unstable with a very short half-life.'}
]
